#!/bin/bash

# v0.1.0

shims="$(pyenv root)/shims"
export PATH="$PATH:$shims"

action=$1
shift

[ "$action" = "usage" ] && {
  echo ""
  echo "  Visualize done tasks:"
  echo "    graph"
  echo "      Draws bar graphs visualizing the number of completed task per day."
  echo "      Optional argument (integer): number of days to visualize (default: 7)"
  echo ""
  exit
}

[ "$action" = "graph" ] && {
	python "$TODO_ACTIONS_DIR"/graph/graph.py "$TODO_FILE" "$DONE_FILE" $@
}
